model_name: "EleutherAI/pythia-1.4b-deduped"
scratch_cache_dir: "/mnt/faster0/rje41/.cache/huggingface"
transformer_lens_name: "pythia-1.4B-deduped"
dataset_loader_n: 3
percentage_prune: 0.05

folder_paths:
    - ../fine-tuning/lingusitic/subject_verb_agreement
    - ../fine-tuning/lingusitic/sva-counter
    - ../fine-tuning/lingusitic/sva-new